spring:
  application:
    name: service_1
eureka:
  client:
    instance:
      preferIpAddress: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9000/eureka}
server:
  port: 9999